name: Git Secrets

on: pull_request

jobs:
  git-secrets:
    name: Git Secrets
    runs-on: ubuntu-latest
    env:
      CI_SUDO_REQUIRED: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci
      - run: git secrets --scan
